### ISSUE TITLE
support for new backend? 

### ISSUE THREAD

**Issue by nia-potato** [kirederik/backstage-k8s-scaffolder-actions#1]
Hi thanks for this plugin, i was wondering if we can migrate to the new backend?

**Comment by kirederik** [comment]
hey @nia-potato, thanks for reaching out

i'll take a look into migrating it 👍🏽

**Comment by billabongrob** [comment]
Hi @kirederik
Larger question: do you think this will be maintained any further?

**Comment by kirederik** [comment]
hey @billabongrob 

I will! I'll try to move things along on here this week. Hold tight!

**Comment by kirederik** [comment]
migrated the plugin to the new backend system, should be available on v0.2.0
